apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-mongodb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-mongodb
  template:
    metadata:
      labels:
        app: auth-mongodb
    spec:
      containers:
      - name: auth-mongodb
        image: mongo
        ports:
        - name: mongodbport
          containerPort: 27017
          protocol: TCP
---
apiVersion: v1
kind: Service
metadata:  
  name: auth-mongodb-srv
spec:
  selector:
    app: auth-mongodb
  ports:
    - name: auth-mongodb
      protocol: TCP
      port:  27017
      targetPort: 27017
 